class Arcadarr < Formula
  include Language::Python::Virtualenv

  desc     "*arr-style ROM library manager for retro games"
  homepage "https://github.com/justinpcosta/arcadarr"
  # Both `url` and `sha256` are rewritten by the release workflow on tag.
  url     "https://github.com/justinpcosta/arcadarr/releases/download/v0.10.0/arcadarr-0.10.0.tar.gz"
  sha256  "946ac4c5de3bf268df26d9306484b77dcd7140fe4a2c8eea4d20124c20174256"
  license "GPL-3.0-or-later"

  depends_on "python@3.11"

  # The full pinned dependency set is regenerated by `pip-compile` on each
  # release and committed alongside this formula. Until that lands the
  # formula declares the top-level deps and lets pip resolve transitives —
  # acceptable for an early-access tap.
  resource "fastapi" do
    url "https://files.pythonhosted.org/packages/source/f/fastapi/fastapi-0.115.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    venv = virtualenv_create(libexec, "python3.11")
    venv.pip_install_and_link buildpath
  end

  service do
    run [opt_bin/"arcadarr"]
    keep_alive true
    log_path   var/"log/arcadarr.log"
    error_log_path var/"log/arcadarr.log"
    environment_variables ARCADARR_DATA_DIR: var/"lib/arcadarr"
  end

  test do
    # `arcadarr --help` is the lightest sanity check — it doesn't open
    # the database or bind a port. Confirms the venv linked, the
    # console_scripts entry point resolves, and the subcommand
    # parser registers everything we expect.
    output = shell_output("#{bin}/arcadarr --help 2>&1")
    assert_match(/serve/, output)
    assert_match(/reset-auth/, output)
    assert_match(/backup/, output)
    assert_match(/migrate-db/, output)

    # `arcadarr platforms` against an empty data dir confirms we can
    # spin up the SQLAlchemy engine and run a query end-to-end. Use
    # the Homebrew test sandbox's testpath so we don't touch the
    # real install's data dir.
    ENV["ARCADARR_DATA_DIR"] = testpath/"arcadarr-data"
    plat = shell_output("#{bin}/arcadarr platforms 2>&1")
    # Empty DB; just confirm the command succeeded — output may be
    # blank if no platforms have been seeded by a server boot yet.
    refute_match(/Traceback|Error/, plat)
  end
end
