class Arcadarr < Formula
  include Language::Python::Virtualenv

  desc     "*arr-style ROM library manager for retro games"
  homepage "https://github.com/arcadarr/arcadarr"
  # Both `url` and `sha256` are rewritten by the release workflow on tag.
  url     "https://github.com/justinpcosta/arcadarr/releases/download/v0.7.0/arcadarr-0.7.0.tar.gz"
  sha256  "8d870360ee024055aacfe44ea4a374194505cbb6808bf6bb88b54b9ffa9c8f83"
  license "MIT"

  depends_on "python@3.11"

  # The full pinned dependency set is regenerated by `pip-compile` on each
  # release and committed alongside this formula. Until that lands the
  # formula declares the top-level deps and lets pip resolve transitives —
  # acceptable for an early-access tap.
  resource "fastapi" do
    url "https://files.pythonhosted.org/packages/source/f/fastapi/fastapi-0.115.0.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    venv = virtualenv_create(libexec, "python3.11")
    venv.pip_install_and_link buildpath
  end

  service do
    run [opt_bin/"arcadarr"]
    keep_alive true
    log_path   var/"log/arcadarr.log"
    error_log_path var/"log/arcadarr.log"
    environment_variables ARCADARR_DATA_DIR: var/"lib/arcadarr"
  end

  test do
    output = shell_output("#{bin}/arcadarr --help 2>&1", 2)
    assert_match(/arcadarr/i, output)
  end
end
